{ "display_name":"Elasticsearch",
  "description": "Monitor Elasticsearch using the SignalFx Smart agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/elasticsearch",
  "code": "https://github.com/signalfx/signalfx-agent",
  "featured": true,
  "logo_small": "/images/repos/elasticsearch/img/integrations_elasticsearch.png",
  "logo_large": "/images/repos/elasticsearch/img/integrations_elasticsearch%402x.png",
  "data_signature": "plugin:\"elasticsearch\"",
  "in_app_categories": ["servicesMonitored"]
}
